import type { MarketingOpportunity, Opportunity, Paper, ResearchInput } from "../types/research";
import { classifyEvidence } from "./scoring";
type Position={title:string;implication:string;opportunity:string;activations:string[]};
const positions:Record<string,Position>={
 "Caffeine":{title:"A caffeine-timing education series",implication:"My audience may want context for questions about coffee timing and sleep, rather than a universal cut-off rule.",opportunity:"Develop an educational caffeine-and-sleep series. Have a qualified reviewer check the papers before including timing guidance; do not use it to claim that my products improve sleep.",activations:["Coffee-timing question carousel","Customer email linking to reviewed caffeine research","Expert interview on caffeine timing and study limitations","Research-led FAQ about coffee and sleep"]},
 "Sleep consistency":{title:"Bring sleep consistency into the conversation",implication:"My audience may benefit from exploring sleep regularity alongside duration. Whether this fills an audience knowledge gap is a hypothesis to test.",opportunity:"Create an educational approach about sleep consistency alongside total sleep time. Avoid presenting a preferred routine as a proven health intervention.",activations:["Sleep regularity explainer","Sleep consistency and duration comparison carousel","Expert interview on sleep schedules","Customer guide to questions to ask about sleep routines"]},
 "Exercise":{title:"Connect movement and recovery education",implication:"My audience may have questions about how exercise timing, intensity, and sleep have been studied.",opportunity:"Build a movement-and-recovery education approach that compares research questions and study populations. Do not promise that an exercise routine or my products will deliver a particular outcome.",activations:["Exercise-and-sleep research guide","Interview with a qualified exercise researcher","Exercise timing FAQ","Customer email introducing recovery research"]},
 "Screen exposure":{title:"A more considered conversation about screens",implication:"My audience may want to distinguish screen exposure, habits, and light-related research questions.",opportunity:"Publish source-led education about screens and sleep, distinguishing the exposures studied from claims about devices or products.",activations:["Screens-before-bed FAQ","Screen exposure research carousel","Expert interview on light and sleep","Customer guide to interpreting screen-related claims"]},
 "Temperature":{title:"Explore the sleep-environment conversation",implication:"My audience may want context about temperature and comfort in sleep research.",opportunity:"Use temperature research as an educational approach. Keep measured study conditions separate from promises about a mattress or recovery product.",activations:["Bedroom temperature explainer","Comfort and sleep research Q&A","Expert interview about thermal conditions","Customer guide to sleep-environment questions"]},
 "Stress":{title:"An expert-led stress and sleep series",implication:"My audience may want careful explanations of the relationship researchers have investigated between stress and sleep.",opportunity:"Create expert-reviewed education on stress and sleep. Explain association and causation, and avoid treatment recommendations or mental-health product claims.",activations:["Expert interview about stress and sleep","Research-led stress and sleep explainer","Customer email directing readers to qualified resources","FAQ explaining association and causation"]},
 "Packaging":{title:"Make packaging choices easier to understand",implication:"My audience may want to understand which materials, comparisons, and conditions packaging research examines.",opportunity:"Create transparent packaging education around the retrieved comparisons. Verify lifecycle boundaries and product-specific data before making environmental claims.",activations:["Packaging comparison guide","Materials research carousel","Interview with a packaging researcher","Customer email explaining packaging trade-offs"]},
 "Circular economy":{title:"Explain what circular consumption involves",implication:"My audience may want concrete context for reuse and circular-economy language.",opportunity:"Develop a source-led explanation of circular consumption and reuse. Keep my brand's practices separate from the outcomes reported in the papers.",activations:["Circular consumption explainer","Reuse questions carousel","Expert interview about circular systems","Customer guide to evaluating circular claims"]},
 "Food waste":{title:"Build a food-waste education approach",implication:"My audience may want practical context for the behaviours or systems studied in food-waste research.",opportunity:"Turn the retrieved food-waste theme into educational messaging after reviewing the findings. Avoid unverified claims about how much waste any tactic prevents.",activations:["Food-waste research guide","Research-question carousel","Expert interview on household food waste","Customer email introducing food-waste evidence"]},
 "Carbon footprint":{title:"Put carbon-footprint claims in context",implication:"My audience may want to understand the scope and assumptions behind carbon-footprint comparisons.",opportunity:"Publish educational material about how footprints are studied. Require separate product-level evidence before advertising a reduction attributable to my brand.",activations:["Carbon-footprint methods explainer","Lifecycle boundary carousel","Expert interview about footprint estimates","Customer guide to reading emissions claims"]},
 "Green claims":{title:"A transparent approach to environmental claims",implication:"My audience may want to know how to evaluate the evidence behind environmental messaging.",opportunity:"Build messaging around source transparency and the limits of green claims. Do not assume that transparency increases sales or that my brand's claims are validated by these papers.",activations:["Environmental claims checklist","Evidence-transparency carousel","Expert interview on greenwashing research","Customer email explaining the sources behind a claim"]},
 "Retrieval practice":{title:"Introduce the questions behind retrieval practice",implication:"My audience may want to understand the learning activities and populations examined in retrieval-practice research.",opportunity:"Develop educational messaging explaining retrieval practice after reviewing the sources. Separate general learning research from claims about my course or tool.",activations:["Retrieval-practice explainer","Learning-methods carousel","Education researcher interview","Student email with reviewed research links"]},
 "Remote work":{title:"An evidence-led remote-work conversation",implication:"My audience may want to compare the contexts and outcomes investigated in remote-work research.",opportunity:"Create a remote-work education approach for team leaders. Discuss organisational context and measurement before recommending a practice or claiming a productivity improvement.",activations:["Remote-work research briefing","Team-leader LinkedIn carousel","Workplace researcher interview","Customer email about remote-work questions"]},
 "Financial literacy":{title:"Build a financial-literacy education series",implication:"My audience may want context for how financial knowledge and decision-making have been investigated.",opportunity:"Create qualified-professional-reviewed financial education. Do not imply that a financial product or an educational tactic delivers better returns.",activations:["Financial-literacy research explainer","Decision-making questions carousel","Qualified financial educator interview","Customer education email"]},
};
export function researchSignals(papers:Paper[]){
 const years=papers.flatMap(p=>p.year!==null?[p.year]:[]).sort((a,b)=>a-b);
 const counts=new Map<number,number>();for(const y of years)counts.set(y,(counts.get(y)||0)+1);
 return {studyCount:papers.length,yearRange:years.length?{earliest:years[0],latest:years[years.length-1]}:null,
 totalCitationCount:papers.reduce((n,p)=>n+p.citedByCount,0),
 researchMomentum:{label:"Unclear" as const,explanation:"These are relevance-selected discovery results, not complete annual counts. Their publication dates cannot establish whether research activity is growing.",
 yearCounts:[...counts].sort((a,b)=>a[0]-b[0]).map(([year,workCount])=>({year,workCount}))}};
}
export function buildMarketingOpportunities(content:Opportunity[],retrieved:Paper[],input:ResearchInput):MarketingOpportunity[]{
 const registry=new Map(retrieved.map(p=>[p.id,p]));
 return content.flatMap(o=>{
  const ids=[...new Set(o.papers.map(p=>p.id))];
  if(ids.some(id=>!registry.has(id)))throw new Error("A marketing opportunity referenced a work outside the retrieved OpenAlex dataset.");
  if(!ids.length)return [];
  const papers=ids.map(id=>registry.get(id)!);
  const anchor=o.suggestedKeywords[0]||input.brief;
  const subject=o.suggestedKeywords[1]||anchor;
  const fallback:Position={title:`Explore ${subject.toLowerCase()} in ${anchor}`,
   implication:`My audience${input.audience?" ("+input.audience+")":""} may find a focused explanation of ${subject.toLowerCase()} in the context of ${anchor} useful. This is an editorial interpretation, not a measured audience finding.`,
   opportunity:`Develop an educational approach about ${subject.toLowerCase()} and ${anchor}, grounded in the supplied sources. Verify findings and applicability before including factual messaging or claims about my brand.`,
   activations:[`${subject} research explainer`,`${subject} question carousel`,`Expert interview about ${subject.toLowerCase()}`,`Customer email introducing ${subject.toLowerCase()} research`]};
  const p=Object.entries(positions).find(([phrase])=>phrase.toLowerCase()===subject.toLowerCase())?.[1]||fallback;
  return [{id:"marketing-"+o.id,sourceOpportunityId:o.id,title:p.title,
   researchContext:`Retrieved OpenAlex works were screened for the ${subject.toLowerCase()} research question in the context of ${anchor}.`,
   evidenceSummary:`${papers.length} relevant academic works support exploration of this question in the retrieved sample. Study findings have not been verified from OpenAlex metadata; no conclusion or statistic is asserted.`,
   audienceImplication:p.implication,marketingOpportunity:p.opportunity,suggestedActivations:p.activations,
   supportingWorkIds:ids,...researchSignals(papers),evidenceStrength:classifyEvidence(papers).strength,
   safetyFlags:o.safetyFlags,interpretationNotice:"Audience relevance and activations are proposals to validate. Academic evidence does not prove that a marketing tactic will increase engagement, conversions, revenue, or ROI."}];
 });
}
